### ISSUE TITLE
Dry-run, measure height of result?

### ISSUE THREAD

**Issue by aried3r** [puzzle/prawn-markup#11]
Hey! I was wondering if there is a way to measure the height of the resulting text like prawn lets you do with `dry_run: true`. We need it for some page-breaking logic and I couldn't find a good way to do this directly.

Any help or pointers would be appreciated.

**Comment by codez** [comment]
Under the hood, prawn-markup calls regular prawn methods. As far as I know, only a few support the dry_run option. So an overall measurement of the resulting height might not be trivial. I am sorry that I cannot help you more.
