### ISSUE TITLE
Inline text color

### ISSUE THREAD

**Issue by sabljak** [puzzle/prawn-markup#15]
Is there a way to have inline color like this:

` markup("hello <color rgb=\"ff0000\">world</color> hello ")`

I can't seem to find the way. It works with `strikethrough`, for example: 

`markup("hello <strikethrough>world</strikethrough> hello")`

**Comment by codez** [comment]
Currently not, but it might be possible to keep `<color>` tags and their attributes in the markup, so prawn can process them.

I will keep the issue open if you would like to create a pull request.
