### ISSUE TITLE
text semantics for underline doesn't seem to be working

### ISSUE THREAD

**Issue by villacerc** [puzzle/prawn-markup#2]
I have the following markup but the underline does not seem to be showing up

<ol>
<li><p><strong>No</strong> <u>pets allowed</u></p></li>
<li><p><strong>No</strong> <u>smoking allowed</u></p></li>
</ol>

the strong element shows up no problem.

note: I can't seem to enclose the markup in a code block as github's WYSIWYG editor parses the markup anyhow but "pets allowed" and "smoking allowed" are enclosed in a "u" element for underline.

![room](https://user-images.githubusercontent.com/7587373/60832206-2626d900-a170-11e9-9b87-7d6e0204fbe3.jpg)

**Comment by codez** [comment]
Thank you for the report. The `u` element and a couple others missed out from the processor. I just published version 0.2.0 containing the fix on rubygems.org.
