### ISSUE TITLE
Few Currency symbols are not supporting

### ISSUE THREAD

**Issue by bantinarvariya** [puzzle/prawn-markup#28]
Currency symbol like Indian rupee is not supporting at time of generation of pdf.  

![Selection_017](https://user-images.githubusercontent.com/37727103/155943485-075d6e97-9744-428b-a184-fbfba1638bf1.png)

here @grand_total is ₹1000

issue is here -> markup("<p>Grand Total: ₹1000</p>")

it support dollar and other few currencies symbols but not supporting rupee currency symbol

**Comment by codez** [comment]
As the error message states, "use external fonts instead of PDF's built-in fonts". This problem is not caused by prawn-markup and can be solved directly with prawn.
