### ISSUE TITLE
Support another "Prawn HTML-esque" tag: <font>?

### ISSUE THREAD

**Issue by allthesignals** [puzzle/prawn-markup#30]
Should we support `<font></font>`?

From the [docs](https://prawnpdf.org/manual.pdf):
```html
This <font size='18'>line</font> uses
<font name='Courier'>all the font tag</font> attributes in
<font character_spacing='2'>a single line</font>.
```

**Comment by codez** [comment]
As it comes with little effort, I would be ok with integrating that, too. The used fonts would have to be registered with prawn manually though.
