### ISSUE TITLE
Set Image width in  markup_options

### ISSUE THREAD

**Issue by asecondwill** [puzzle/prawn-markup#44]
How can I set an image width in the markup_options ?
```
@document.markup_options = { 
 img: {width: '80%'}
}
```

This does not seem to work.  If I pass in a good sized image (say 900px wide) it goes off the page, and if i reduce it enough to show on the page (450px), it isnt a good enough quality.  

Is this possible to do ?  I can't set the width inline because I'm getting the text from markdown sources.

**Comment by codez** [comment]
There is no possibility to set image width in the markup options, because they apply to the entire document and not to single elements. I guess you would have to parse your html and insert `style="width: 100%;"` attributes into the `img` tags.
