### ISSUE TITLE
Using the `img` width attribute

### ISSUE THREAD

**Issue by rebelcolony** [puzzle/prawn-markup#47]
So I'm using HTML from tinyMCE a WYSIWYG and I have images like this:
`"<p><img src=\"http://localhost:3000/....jpg\" alt=\"\" width=\"72\" height=\"101\"></p>"`

The image itself loads but the height & width attributes do nothing. Any suggestions on how to get the image dimensions?

**Comment by codez** [comment]
Currently, those attributes are not used, only the width in the style attribute.

It should be possible to integrate that into prawn-markup.

**Comment by rebelcolony** [comment]
okay, I'll look into it and make a PR if it works out.

**Comment by codez** [comment]
Great, a pull request is very welcome.
