### ISSUE TITLE
Same margin before and after a list between paragraphs?

### ISSUE THREAD

**Issue by aried3r** [puzzle/prawn-markup#7]
Hey and thanks for this gem!

I'm currently playing around with this gem and was wondering if there is a way to have the same bottom and top margin/padding in a list surrounded by paragraphs?

```HTML
<p>Top paragraph</p>
<!-- Add a margin here -->
<ul>
  <li><p>A</p></li>
  <li><p>list</p></li>
  <li><p>with</p></li>
  <li><p>elements</p></li>
</ul>
<!-- Add same margin here -->
<p>Bottom Paragraph</p>
```

### Expected result (HTML rendered in a browser)
<img width="156" alt="Screenshot 2020-03-03 at 16 24 25" src="https://user-images.githubusercontent.com/1301152/75790428-7db32e00-5d6b-11ea-8d12-86461cef5cf6.png">

### Actual result

```Ruby
BASE_LINE_GRID = 13

markup_options = {
    text: {
        leading: BASE_LINE_GRID - font.height_at(8.5),
        # Default margin_bottom seems like a sensible default, let's keep
        # it for now.
        # margin_bottom: 0 # Margin after each <p>, <ol>, <ul> or <table>
    },
    list: {
        vertical_margin: 0, # margin at the top and the bottom of the list
        bullet: {
            margin: 0 # Margin before bullet
        },
        content: {
            leading: BASE_LINE_GRID - font.height_at(8.5), # Vertical padding between list items
            margin: 4 # Between bullet and content
        }
    }
}
```

<img width="120" alt="Screenshot 2020-03-03 at 16 09 37" src="https://user-images.githubusercontent.com/1301152/75789252-b2be8100-5d69-11ea-842a-629470c72638.png">

I assume what I'm seeing here is the `margin_bottom` of the _"Top Paragraph"_ `<p>` + an additional padding/margin on top of the list (although `vertical_margin` is 0).

If I change it `text: { margin_bottom: 0 }` of course the margins at the bottom of the first `<p>` are gone, and so is the margin at the bottom of the `<ul>`. However there is still a margin before the list and I'm not sure where it's coming from.

<img width="118" alt="Screenshot 2020-03-03 at 16 17 27" src="https://user-images.githubusercontent.com/1301152/75790190-1c8b5a80-5d6b-11ea-96dc-15931c84bfe6.png">

Even when I set everything (well, I guess not _everything_ otherwise it'd be gone) to 0, there's still a distance between the top paragraph and the bottom one.

```Ruby
markup_options = {
    text: {
        leading: 0
        margin_bottom: 0 # Margin after each <p>, <ol>, <ul> or <table>
    },
    list: {
        vertical_margin: 0, # margin at the top and the bottom of the list
        bullet: {
            margin: 0 # Margin before bullet
        },
        content: {
            leading: 0 # Vertical padding between list items
            margin: 4 # Between bullet and content
        }
    }
}
```

<img width="117" alt="Screenshot 2020-03-03 at 16 22 08" src="https://user-images.githubusercontent.com/1301152/75790332-56f4f780-5d6b-11ea-818d-432462267cbe.png">

**Comment by codez** [comment]
I found an unexpected move_down in the code of prawn table, which is used to render lists. Could you try the branch adjust_list_gaps with your example to see if it fixes your issue?

**Comment by aried3r** [comment]
Hey! Thanks for the quick reply. It seems that it doesn't fix the issue. I dug around a bit more (and hopefully don't confuse the screenshots), and I'm not quite sure which values get mixed up.

This is with all leadings set to 0. That definitely doesn't seem correct to me.
<img width="372" alt="Screenshot 2020-03-06 at 10 35 59" src="https://user-images.githubusercontent.com/1301152/76072864-01059700-5f99-11ea-994d-ac36b1b5ef2c.png">

Thats with `[:text][:leading]` set properly.
<img width="367" alt="Screenshot 2020-03-06 at 10 36 18" src="https://user-images.githubusercontent.com/1301152/76072902-0f53b300-5f99-11ea-9bfc-3e78ead59a43.png">

This, IIRC, is with `[:text][:leading]` set to 0, and `[:list][:leading]` set properly.
<img width="240" alt="Screenshot 2020-03-06 at 10 51 16" src="https://user-images.githubusercontent.com/1301152/76072940-1ed2fc00-5f99-11ea-9711-4eeb4e7d25b4.png">

Same as above but without borders to see what it looks like.
<img width="240" alt="Screenshot 2020-03-06 at 10 54 21" src="https://user-images.githubusercontent.com/1301152/76073001-3a3e0700-5f99-11ea-92bc-72ab5b2cafb6.png">

Here's two with horizontal lines being drawn before and after the text and borders around the list.
`[:text][:leading]` is 0, `[:list][:leading]` is correctly set, `[:text][:margin_bottom]` is 0, `[:list][:vertical_margin]` is 0.
<img width="331" alt="Screenshot 2020-03-06 at 11 10 43" src="https://user-images.githubusercontent.com/1301152/76074274-6490c400-5f9b-11ea-9a47-4bd2eb047582.png">
And once without the table borders.
<img width="296" alt="Screenshot 2020-03-06 at 11 11 32" src="https://user-images.githubusercontent.com/1301152/76074277-665a8780-5f9b-11ea-8a8b-eecab044ea18.png">

Sorry, that it's a bit messy, I was just quickly playing around with it. I should probably at this point just write a test PDF.

Anyway, `prawn_list_gap` in your branch is `1.8062500000000001` in my case which isn't much (btw, we could use `move_up` instead of `move_down` with a negative number). So I think it's a case where the leading of text and the leading of lists are somehow interfering, but I might be wrong. WDYT?

**Comment by codez** [comment]
Thanks for your analysis. Are you actually using a special font or is this the standard Helvetica in your example? This really seems to be some font spacing issue depending on descenders, ascenders and line gaps. Unfortunately, I am not really an expert in this field. Probably some more digging in the Prawn/Prawn-Table source code would be necessary.

There are various specs to start from. I used https://github.com/puzzle/prawn-markup/blob/631e6b461a78eba2e1f40fd59f8d8c932bcbf9b3/spec/prawn/markup/processor/lists_spec.rb#L176 to play around. Inserting `lookatit` calls after `processor.parse` lines will directly open the generated PDF on Linux or Mac when running the specs.

**Comment by aried3r** [comment]
> Are you actually using a special font or is this the standard Helvetica in your example?

I'm using "Gilroy", here's the same with Helvetica: 
`[:text][:leading] = 0`,  `[:text][:margin_bottom] = 0`, `[:list][:leading] = 13 - font.height_at(8.5)` (13 is the height of our lines)

<img width="235" alt="Screenshot 2020-03-06 at 12 00 22" src="https://user-images.githubusercontent.com/1301152/76078135-58f4cb80-5fa2-11ea-9bfe-6cc075c01e98.png">

**Comment by aried3r** [comment]
Ok, a more complete example:

```Ruby
BASE_LINE_GRID = 13

markup_options = {
    text: {
        font: 'Helvetica',
        size: 8.5,
        leading: BASE_LINE_GRID - font.height_at(8.5)
        # margin_bottom: 0 # Margin after each <p>, <ol>, <ul> or <table>
    },
    list: {
        vertical_margin: 0, # margin at the top and the bottom of the list
        bullet: {
            margin: 0 # Margin before bullet
        },
        content: {
            leading: BASE_LINE_GRID - font.height_at(8.5), # Vertical padding between list items
            margin: 4 # Between bullet and content
        }
    }
}
```

And I added another `pdf.move_up(text_leading * 2)` to your `pdf.move_down(-prawn_list_gap)`. I'm not sure if that should be something else like `text_leading + list_leading` (`list_leading` doesn't exist yet) instead. Have to think about it some more.

But this is the result:
<img width="480" alt="Screenshot 2020-03-06 at 12 09 36" src="https://user-images.githubusercontent.com/1301152/76079124-4c717280-5fa4-11ea-946b-0de5a9942565.png">

As you can see, I have quite sophisticated graphics skills. The lines _almost_ line up, haha.

**Comment by codez** [comment]
I guess I found the issue. The problem seems to be that the `move_down` in `Prawn::Table::Cell::Text#draw_content` and the used `with_font` do not use the actual cell's font size. So our `prawn_list_gap` is calculated from the cell font size, the one used in `draw_content` from the document font size. This also affects regular tables and is well visible when using a much larger font size in cells, where the vertical alignment is quite out of place. 

Probably we should open an issue in prawn-table?

**Comment by codez** [comment]
Created https://github.com/prawnpdf/prawn-table/issues/120.

Considering the last commit to the prawn-table code was 4 years ago, I will fix it here anyways.

**Comment by codez** [comment]
Pushed a new commit to https://github.com/puzzle/prawn-markup/tree/adjust_list_gaps

**Comment by codez** [comment]
@aried3r did you get a chance to test the changes? If everything is ok, I will cut a new version of the gem.

**Comment by aried3r** [comment]
Hey! So far I haven't, but I hope to take a closer look either tomorrow or beginning of next week.

Thanks for your work so far!

**Comment by aried3r** [comment]
I had a chance to test your changes, it seems to work! I think the `move_up` is not technically correct (see: https://github.com/prawnpdf/prawn/issues/539, texts are not centered anymore within their cells), but it seems that way we actually get the result we expect, equal margins on top and bottom.

Result:
<img width="428" alt="Screenshot 2020-03-16 at 16 15 04" src="https://user-images.githubusercontent.com/1301152/76773663-223d6300-67a3-11ea-9cee-09882dba0c6c.png">

With table borders:
<img width="497" alt="Screenshot 2020-03-16 at 16 18 16" src="https://user-images.githubusercontent.com/1301152/76773668-249fbd00-67a3-11ea-845b-3be69a781324.png">

**Comment by codez** [comment]
Great, I'm about to release a new version.
