### ISSUE TITLE
Parsing ActionText content  

### ISSUE THREAD

**Issue by goulvench** [puzzle/prawn-markup#9]
Hi, and first of all thanks for this great extension to Prawn!

I'm using ActionText which relies on ActiveStorage for images, and generates the following markup:

```html
<action-text-attachment 
  sgid="[signed_global_id]" 
  content-type="image/png" 
  url="http://localhost:3000/rails/active_storage/blobs/[blob_key]/filename.png" 
  filename="caption_or_filename.png" 
  filesize="40555" 
  width="903" 
  height="80" 
  previewable="true" 
  presentation="gallery"
>
  <figure class="attachment attachment--preview attachment--png">
    <img src="http://127.0.0.1:3000/rails/active_storage/representations/[blob_key]/[temp_key]/filename.png">
    <figcaption class="attachment__caption">
        <span class="attachment__name">caption_or_filename.png</span>
        <span class="attachment__size">39,6 ko</span>
    </figcaption>
  </figure>
</action-text-attachment>
```

Prawn-markup loads these images through HTTP (`URI.parse(src).open`, called in `load_remote_image`). While this works, it generates avoidable HTTP traffic in production, and causes deadlocks on development machines because fetching image data must wait for the main process to complete, which in turn needs images to have finished downloading.

I was able to load ActiveStorage images into a Prawn document outside of Prawn-Markup using the following syntax, as recommended in [Prawn issue #1111](https://github.com/prawnpdf/prawn/issues/1111):

```ruby
begin
    image StringIO.open(@report.logo.download)
rescue ActiveStorage::FileNotFoundError
    # Handle image not found error
end
```

However, given that Prawn-Markup's image loader lambda only receives the src attribute, we cannot find the corresponding  ActiveStorage blob and pass the results of calling `download` on it to `StringIO.open`.

I'm working on a way to add action-text images to Prawn-Markup but would be interested to know if someone else has looked into it, and if this would be considered a useful addition to the library. Your thoughts?

**Comment by codez** [comment]
I don't use ActiveStorage so far, but isn't the blob key part of the `src` URL? If Rails can figure out which file to return based on this URL, you could too?

**Comment by goulvench** [comment]
@codez Indeed, I was able to go from URL back to ActiveStorage blob using a loader. Hadn't thought about that but it's way easier, thanks!

Here is how to setup Prawn-Markup to load ActiveStorage images in Rails 6 without making HTTP requests:

```ruby
document.markup_options = {
    image: { loader: ->(src) { StringIO.new(ActiveStorage::Blob.find_signed(src.split('/')[6]).download) } }
}
```

Looks brittle but it works. `StringIO` is required, otherwise we get a `Pathname contains null byte` error.

**Comment by codez** [comment]
Great to know it worked! I will add the example to the Readme.

**Comment by atstockland** [comment]
> @codez Indeed, I was able to go from URL back to ActiveStorage blob using a loader. Hadn't thought about that but it's way easier, thanks!
> 
> Here is how to setup Prawn-Markup to load ActiveStorage images in Rails 6 without making HTTP requests:
> 
> ```ruby
> document.markup_options = {
>     image: { loader: ->(src) { StringIO.new(ActiveStorage::Blob.find_signed(src.split('/')[6]).download) } }
> }
> ```
> 
> Looks brittle but it works. `StringIO` is required, otherwise we get a `Pathname contains null byte` error.

How could you control the size of the image?
